export enum TipoOperacionFinanciera {
  CAMBIO_DIVISA = 'CAMBIO_DIVISA',
  DEPOSITO_BANCARIO = 'DEPOSITO_BANCARIO',
  RETIRO_BANCARIO = 'RETIRO_BANCARIO',
  TRANSFERENCIA_ENTRE_CAJAS = 'TRANSFERENCIA_ENTRE_CAJAS',
}

export enum DiferenciaDestinoTipo {
  GASTO = 'GASTO',
  VALE = 'VALE',
  IGNORAR = 'IGNORAR',
}
