export enum AsistenciaEstado {
  PRESENTE = 'PRESENTE',
  AUSENTE = 'AUSENTE',
  TARDANZA = 'TARDANZA',
  MEDIA_FALTA = 'MEDIA_FALTA',
  JUSTIFICADO = 'JUSTIFICADO',
  FERIADO = 'FERIADO',
  VACACION = 'VACACION',
}
