export enum FuncionarioDocumentoTipo {
  CEDULA = 'CEDULA',
  CONTRATO = 'CONTRATO',
  CERTIFICADO = 'CERTIFICADO',
  CV = 'CV',
  ANTECEDENTES = 'ANTECEDENTES',
  CARNET_SALUD = 'CARNET_SALUD',
  TITULO_ACADEMICO = 'TITULO_ACADEMICO',
  OTRO = 'OTRO'
}
