export enum MotivoEgreso {
  RENUNCIA = 'RENUNCIA',
  DESPIDO_JUSTIFICADO = 'DESPIDO_JUSTIFICADO',
  DESPIDO_INJUSTIFICADO = 'DESPIDO_INJUSTIFICADO',
  MUTUO_ACUERDO = 'MUTUO_ACUERDO',
  JUBILACION = 'JUBILACION',
  FALLECIMIENTO = 'FALLECIMIENTO',
  OTRO = 'OTRO'
}
