export enum PenalizacionTipo {
  TARDANZA = 'TARDANZA',
  AUSENCIA = 'AUSENCIA',
  QUEJA_CLIENTE = 'QUEJA_CLIENTE',
  AMBIENTE_LABORAL = 'AMBIENTE_LABORAL',
  DANIO_MATERIAL = 'DANIO_MATERIAL',
  COMISION_DESCUENTO = 'COMISION_DESCUENTO',
  OTRO = 'OTRO',
}
