import { Observable } from 'rxjs';

import { Printer } from './entities/printer.entity';
import { Persona } from './entities/personas/persona.entity';
import { DocumentoTipo } from './entities/personas/documento-tipo.enum';
import { PersonaTipo } from './entities/personas/persona-tipo.enum';
import { Usuario } from './entities/personas/usuario.entity';
import { Role } from './entities/personas/role.entity';
import { UsuarioRole } from './entities/personas/usuario-role.entity';
import { TipoCliente } from './entities/personas/tipo-cliente.entity';
import { Cliente } from './entities/personas/cliente.entity';
import { LoginSession } from './entities/auth/login-session.entity';
import { DeviceInfo } from '../services/auth.service';
import { MonedaBillete } from './entities/financiero/moneda-billete.entity';
import { MonedaCambio } from './entities/financiero/moneda-cambio.entity';
import { Conteo } from './entities/financiero/conteo.entity';
import { ConteoDetalle } from './entities/financiero/conteo-detalle.entity';
import { Dispositivo } from './entities/financiero/dispositivo.entity';
import { Caja, CajaEstado } from './entities/financiero/caja.entity';
import { CajaMoneda } from './entities/financiero/caja-moneda.entity';
import { Proveedor } from './entities/compras/proveedor.entity';
import { Compra } from './entities/compras/compra.entity';
import { CompraDetalle } from './entities/compras/compra-detalle.entity';
import { Pago } from './entities/compras/pago.entity';
import { PagoDetalle } from './entities/compras/pago-detalle.entity';
import { ProveedorProducto } from './entities/compras/proveedor-producto.entity';
import { FormasPago } from './entities/compras/forma-pago.entity';
import { PrecioDelivery } from './entities/ventas/precio-delivery.entity';
import { Delivery, DeliveryEstado } from './entities/ventas/delivery.entity';
import { Venta, VentaEstado } from './entities/ventas/venta.entity';
import { VentaItem } from './entities/ventas/venta-item.entity';
import { PdvGrupoCategoria } from './entities/ventas/pdv-grupo-categoria.entity';
import { PdvCategoria } from './entities/ventas/pdv-categoria.entity';
import { PdvCategoriaItem } from './entities/ventas/pdv-categoria-item.entity';
import { PdvItemProducto } from './entities/ventas/pdv-item-producto.entity';
import { PdvConfig } from './entities/ventas/pdv-config.entity';
import { PdvMesa } from './entities/ventas/pdv-mesa.entity';
import { Sector } from './entities/ventas/sector.entity';
import { Reserva } from './entities/ventas/reserva.entity';
import { Moneda } from './entities/financiero/moneda.entity';
import { TipoPrecio } from './entities/financiero/tipo-precio.entity';
import { Familia } from './entities/productos/familia.entity';
import { Subfamilia } from './entities/productos/subfamilia.entity';
import { Producto } from './entities/productos/producto.entity';
import { Presentacion } from './entities/productos/presentacion.entity';
import { CodigoBarra } from './entities/productos/codigo-barra.entity';
import { PrecioVenta } from './entities/productos/precio-venta.entity';
import { PrecioCosto } from './entities/productos/precio-costo.entity';
import { Receta } from './entities/productos/receta.entity';
import { RecetaIngrediente } from './entities/productos/receta-ingrediente.entity';
import { StockMovimiento } from './entities/productos/stock-movimiento.entity';
import { ConversionMoneda } from './entities/productos/conversion-moneda.entity';
import { ConfiguracionMonetaria } from './entities/productos/configuracion-monetaria.entity';
import { Observacion } from './entities/productos/observacion.entity';
import { ProductoObservacion } from './entities/productos/producto-observacion.entity';
import { Adicional } from './entities/productos/adicional.entity';
import { RecetaAdicionalVinculacion } from './entities/productos/receta-adicional-vinculacion.entity';
import { RecetaIngredienteIntercambiable } from './entities/productos/receta-ingrediente-intercambiable.entity';

export interface LoginResult {
  success: boolean;
  usuario?: Usuario;
  token?: string;
  message?: string;
  sessionId?: number;
}

export interface ClienteFilters {
  nombre?: string;
  ruc?: string;
  tipoClienteId?: number;
  activo?: boolean;
  conCredito?: boolean;
}

/**
 * Abstracción del repositorio de datos.
 *
 * F2 (cliente/servidor): permite swap entre `RepositoryIpcService` (modo
 * standalone/server, usa Electron IPC) y `RepositoryHttpService` (modo
 * cliente, llama HTTP al server). Componentes inyectan `RepositoryService`
 * (esta abstract class actúa como token DI) y la factory en `app.module.ts`
 * decide la impl en runtime según `app-settings.mode`.
 *
 * Auto-generada con `scripts/generate-repository-abstract.py` desde la
 * implementación actual. Si agregás un método a la impl (RepositoryIpcService),
 * regenerá este archivo.
 */
export abstract class RepositoryService {
  abstract getCurrentUser(): Observable<Usuario | null>;
  abstract getCurrentUserId(): number | undefined;
  abstract setCurrentUser(usuario: Usuario | null): void;
  abstract getPersonas(): Observable<Persona[]>;
  abstract getPersona(personaId: number): Observable<Persona>;
  abstract createPersona(personaData: Partial<Persona>): Observable<Persona>;
  abstract updatePersona(personaId: number, personaData: Partial<Persona>): Observable<any>;
  abstract deletePersona(personaId: number): Observable<any>;
  abstract getUsuarios(): Observable<Usuario[]>;
  abstract getUsuario(usuarioId: number): Observable<Usuario>;
  abstract createUsuario(usuarioData: Partial<Usuario>): Observable<Usuario>;
  abstract updateUsuario(usuarioId: number, usuarioData: Partial<Usuario>): Observable<any>;
  abstract deleteUsuario(usuarioId: number): Observable<any>;
  abstract getRoles(): Observable<Role[]>;
  abstract getRole(roleId: number): Observable<Role>;
  abstract createRole(roleData: Partial<Role>): Observable<Role>;
  abstract updateRole(roleId: number, roleData: Partial<Role>): Observable<any>;
  abstract deleteRole(roleId: number): Observable<any>;
  abstract getUsuarioRoles(usuarioId: number): Observable<UsuarioRole[]>;
  abstract assignRoleToUsuario(usuarioId: number, roleId: number): Observable<any>;
  abstract removeRoleFromUsuario(usuarioRoleId: number): Observable<any>;
  abstract getTipoClientes(): Observable<TipoCliente[]>;
  abstract getTipoCliente(tipoClienteId: number): Observable<TipoCliente>;
  abstract createTipoCliente(tipoClienteData: Partial<TipoCliente>): Observable<TipoCliente>;
  abstract updateTipoCliente(tipoClienteId: number, tipoClienteData: Partial<TipoCliente>): Observable<any>;
  abstract deleteTipoCliente(tipoClienteId: number): Observable<any>;
  abstract getClientes(filters?: ClienteFilters): Observable<Cliente[]>;
  abstract getCliente(clienteId: number): Observable<Cliente>;
  abstract createCliente(clienteData: Partial<Cliente>): Observable<Cliente>;
  abstract updateCliente(clienteId: number, clienteData: Partial<Cliente>): Observable<any>;
  abstract deleteCliente(clienteId: number): Observable<any>;
  abstract getPrinters(): Observable<any[]>;
  abstract addPrinter(printer: any): Observable<any>;
  abstract updatePrinter(printerId: number, printer: any): Observable<any>;
  abstract deletePrinter(printerId: number): Observable<any>;
  abstract printReceipt(orderId: number, printerId: number): Observable<any>;
  abstract printTestPage(printerId: number): Observable<any>;
  abstract getUsuariosPaginated(page: number, pageSize: number, filters?: { nickname?: string; nombrePersona?: string; activo?: string | boolean }): Observable<{items: Usuario[], total: number}>;
  abstract login(loginData: {nickname: string, password: string, deviceInfo: DeviceInfo}): Observable<LoginResult>;
  abstract validateCredentials(data: { nickname: string, password: string }): Observable<any>;
  abstract logout(sessionId: number): Observable<boolean>;
  abstract updateSessionActivity(sessionId: number): Observable<boolean>;
  abstract getLoginSessions(usuarioId: number): Observable<LoginSession[]>;
  abstract uploadImage(formData: FormData): Observable<{ imageUrl: string }>;
  abstract deleteProfileImage(imageUrl: string): Observable<boolean>;
  abstract saveFile(input: { carpeta: string; base64: string; fileName: string; generateThumbnails?: boolean }): Observable<{ url: string; fileName: string; mimeType: string; tamanoBytes: number; thumbUrl?: string; mediumUrl?: string }>;
  abstract deleteFile(url: string): Observable<{ ok: boolean }>;
  abstract readFileBase64(url: string): Observable<{ base64: string; mimeType: string }>;
  abstract openFileWithSystem(url: string): Observable<{ ok: boolean; error?: string }>;
  abstract getAdjuntos(params: { entidadTipo: string; entidadId: number }): Observable<any[]>;
  abstract createAdjunto(data: { entidadTipo: string; entidadId: number; tipo?: string; archivoUrl: string; nombreArchivo: string; mimeType?: string; tamanoBytes?: number; observacion?: string }): Observable<any>;
  abstract updateAdjunto(id: number, data: { tipo?: string; observacion?: string }): Observable<any>;
  abstract deleteAdjunto(id: number): Observable<{ success: boolean; message?: string }>;
  abstract getMonedas(): Observable<Moneda[]>;
  abstract getMoneda(monedaId: number): Observable<Moneda>;
  abstract getMonedaPrincipal(): Observable<Moneda>;
  abstract createMoneda(monedaData: Partial<Moneda>): Observable<Moneda>;
  abstract updateMoneda(monedaId: number, monedaData: Partial<Moneda>): Observable<any>;
  abstract deleteMoneda(monedaId: number): Observable<any>;
  abstract getMonedasBilletes(): Observable<MonedaBillete[]>;
  abstract getMonedaBillete(monedaBilleteId: number): Observable<MonedaBillete>;
  abstract createMonedaBillete(monedaBilleteData: Partial<MonedaBillete>): Observable<MonedaBillete>;
  abstract updateMonedaBillete(monedaBilleteId: number, monedaBilleteData: Partial<MonedaBillete>): Observable<any>;
  abstract deleteMonedaBillete(monedaBilleteId: number): Observable<any>;
  abstract getConteos(): Observable<Conteo[]>;
  abstract getConteo(conteoId: number): Observable<Conteo>;
  abstract createConteo(conteoData: Partial<Conteo>): Observable<Conteo>;
  abstract updateConteo(conteoId: number, conteoData: Partial<Conteo>): Observable<any>;
  abstract deleteConteo(conteoId: number): Observable<any>;
  abstract getConteoDetalles(conteoId: number): Observable<ConteoDetalle[]>;
  abstract getConteoDetalle(conteoDetalleId: number): Observable<ConteoDetalle>;
  abstract createConteoDetalle(conteoDetalleData: Partial<ConteoDetalle>): Observable<ConteoDetalle>;
  abstract updateConteoDetalle(conteoDetalleId: number, conteoDetalleData: Partial<ConteoDetalle>): Observable<any>;
  abstract deleteConteoDetalle(conteoDetalleId: number): Observable<any>;
  abstract getDispositivos(): Observable<Dispositivo[]>;
  abstract getDispositivo(dispositivoId: number): Observable<Dispositivo>;
  abstract createDispositivo(dispositivoData: Partial<Dispositivo>): Observable<Dispositivo>;
  abstract updateDispositivo(dispositivoId: number, dispositivoData: Partial<Dispositivo>): Observable<any>;
  abstract deleteDispositivo(dispositivoId: number): Observable<any>;
  abstract getCajas(): Observable<Caja[]>;
  abstract getCajaAbiertaByUsuario(usuarioId: number): Observable<Caja>;
  abstract getCaja(cajaId: number): Observable<Caja>;
  abstract createCaja(cajaData: Partial<Caja>): Observable<Caja>;
  abstract updateCaja(cajaId: number, cajaData: Partial<Caja>): Observable<any>;
  abstract deleteCaja(cajaId: number): Observable<any>;
  abstract getCajaByDispositivo(dispositivoId: number): Observable<Caja[]>;
  abstract getCajasMonedas(): Observable<CajaMoneda[]>;
  abstract getCajaMoneda(cajaMonedaId: number): Observable<CajaMoneda>;
  abstract createCajaMoneda(cajaMonedaData: Partial<CajaMoneda>): Observable<CajaMoneda>;
  abstract updateCajaMoneda(cajaMonedaId: number, cajaMonedaData: Partial<CajaMoneda>): Observable<any>;
  abstract deleteCajaMoneda(cajaMonedaId: number): Observable<any>;
  abstract saveCajasMonedas(updates: any[]): Observable<any>;
  abstract getMonedasCambio(): Observable<MonedaCambio[]>;
  abstract getMonedasCambioByMonedaOrigen(monedaOrigenId: number): Observable<MonedaCambio[]>;
  abstract getMonedaCambio(monedaCambioId: number): Observable<MonedaCambio>;
  abstract getValorEnMonedaPrincipal(monedaId: number, valor: number): Observable<number>;
  abstract createMonedaCambio(monedaCambioData: Partial<MonedaCambio>): Observable<MonedaCambio>;
  abstract updateMonedaCambio(monedaCambioId: number, monedaCambioData: Partial<MonedaCambio>): Observable<any>;
  abstract deleteMonedaCambio(monedaCambioId: number): Observable<any>;
  abstract getMonedaCambioByMonedaPrincipal(): Observable<MonedaCambio>;
  abstract getProveedores(): Observable<Proveedor[]>;
  abstract getProveedor(proveedorId: number): Observable<Proveedor>;
  abstract createProveedor(proveedorData: Partial<Proveedor>): Observable<Proveedor>;
  abstract updateProveedor(proveedorId: number, proveedorData: Partial<Proveedor>): Observable<any>;
  abstract deleteProveedor(proveedorId: number): Observable<any>;
  abstract searchProveedoresByText(searchText: string): Observable<Proveedor[]>;
  abstract getCompras(): Observable<Compra[]>;
  abstract getCompra(compraId: number): Observable<Compra>;
  abstract createCompra(compraData: Partial<Compra>): Observable<Compra>;
  abstract updateCompra(compraId: number, compraData: Partial<Compra>): Observable<any>;
  abstract deleteCompra(compraId: number): Observable<any>;
  abstract getComprasPaginado(params: any): Observable<{ items: Compra[]; total: number; page: number; pageSize: number }>;
  abstract createCompraBorrador(data: any): Observable<Compra>;
  abstract updateCompraBorrador(id: number, data: any): Observable<Compra>;
  abstract finalizarCompra(id: number, payload: any): Observable<Compra>;
  abstract anularCompra(id: number, motivo: string): Observable<{ success: boolean }>;
  abstract getCompraDetalles(compraId: number): Observable<CompraDetalle[]>;
  abstract getCompraDetalle(compraDetalleId: number): Observable<CompraDetalle>;
  abstract createCompraDetalle(compraDetalleData: Partial<CompraDetalle>): Observable<CompraDetalle>;
  abstract updateCompraDetalle(compraDetalleId: number, compraDetalleData: Partial<CompraDetalle>): Observable<any>;
  abstract deleteCompraDetalle(compraDetalleId: number): Observable<any>;
  abstract getPagos(): Observable<Pago[]>;
  abstract getPago(pagoId: number): Observable<Pago>;
  abstract getPagosByCompra(compraId: number): Observable<Pago[]>;
  abstract createPago(pagoData: Partial<Pago>): Observable<Pago>;
  abstract updatePago(pagoId: number, pagoData: Partial<Pago>): Observable<any>;
  abstract deletePago(pagoId: number): Observable<any>;
  abstract getPagoDetalles(pagoId: number): Observable<PagoDetalle[]>;
  abstract getPagoDetalle(pagoDetalleId: number): Observable<PagoDetalle>;
  abstract createPagoDetalle(pagoDetalleData: Partial<PagoDetalle>): Observable<PagoDetalle>;
  abstract updatePagoDetalle(pagoDetalleId: number, pagoDetalleData: Partial<PagoDetalle>): Observable<any>;
  abstract deletePagoDetalle(pagoDetalleId: number): Observable<any>;
  abstract getProveedorProductos(): Observable<ProveedorProducto[]>;
  abstract getProveedorProductosByProveedor(proveedorId: number): Observable<ProveedorProducto[]>;
  abstract getProveedorProducto(proveedorProductoId: number): Observable<ProveedorProducto>;
  abstract createProveedorProducto(proveedorProductoData: Partial<ProveedorProducto>): Observable<ProveedorProducto>;
  abstract updateProveedorProducto(proveedorProductoId: number, proveedorProductoData: Partial<ProveedorProducto>): Observable<any>;
  abstract deleteProveedorProducto(proveedorProductoId: number): Observable<any>;
  abstract getProveedorProductosPaginado(params: { proveedorId: number; search?: string; page?: number; pageSize?: number }): Observable<{ items: any[]; total: number; page: number; pageSize: number }>;
  abstract getUltimasComprasProducto(params: { productoId: number; page?: number; pageSize?: number }): Observable<{ items: any[]; total: number; page: number; pageSize: number }>;
  abstract getUltimoCostoProducto(params: { productoId: number; proveedorId?: number | null }): Observable<{ ultimoCosto: number | null; fuente: 'PROVEEDOR_PRODUCTO' | 'COMPRA_DETALLE' | null; fecha: string | Date | null }>;
  abstract getFormasPago(): Observable<FormasPago[]>;
  abstract getFormaPago(formaPagoId: number): Observable<FormasPago>;
  abstract createFormaPago(formaPagoData: Partial<FormasPago>): Observable<FormasPago>;
  abstract updateFormaPago(formaPagoId: number, formaPagoData: Partial<FormasPago>): Observable<any>;
  abstract deleteFormaPago(formaPagoId: number): Observable<any>;
  abstract updateFormasPagoOrder(updates: { id: number, orden: number }[]): Observable<any>;
  abstract getPreciosDelivery(): Observable<PrecioDelivery[]>;
  abstract getPrecioDelivery(precioDeliveryId: number): Observable<PrecioDelivery>;
  abstract createPrecioDelivery(precioDeliveryData: Partial<PrecioDelivery>): Observable<PrecioDelivery>;
  abstract updatePrecioDelivery(precioDeliveryId: number, precioDeliveryData: Partial<PrecioDelivery>): Observable<any>;
  abstract deletePrecioDelivery(precioDeliveryId: number): Observable<any>;
  abstract getDeliveries(): Observable<Delivery[]>;
  abstract getDeliveriesByEstado(estado: DeliveryEstado): Observable<Delivery[]>;
  abstract getDelivery(deliveryId: number): Observable<Delivery>;
  abstract createDelivery(deliveryData: Partial<Delivery>): Observable<Delivery>;
  abstract updateDelivery(deliveryId: number, deliveryData: Partial<Delivery>): Observable<any>;
  abstract deleteDelivery(deliveryId: number): Observable<any>;
  abstract getDeliveriesByCaja(cajaId: number, filtros?: any): Observable<{ data: any[], total: number }>;
  abstract buscarClientePorTelefono(telefono: string): Observable<any>;
  abstract buscarClientesPorTelefono(telefono: string): Observable<any[]>;
  abstract crearClienteRapido(data: { telefono: string; nombre?: string; direccion?: string }): Observable<any>;
  abstract cerrarVentasAbiertasMesa(mesaId: number, estado: string): Observable<number>;
  abstract getVentas(): Observable<Venta[]>;
  abstract getVentasByDateRange(desde: string, hasta: string, filtros?: any): Observable<{ data: Venta[], total: number }>;
  abstract getVentasByEstado(estado: VentaEstado): Observable<Venta[]>;
  abstract getVentasByCaja(cajaId: number): Observable<Venta[]>;
  abstract getResumenCaja(cajaId: number): Observable<any>;
  abstract getVentasTotalByCaja(cajaId: number): Observable<any[]>;
  abstract getVenta(ventaId: number): Observable<Venta>;
  abstract createVenta(ventaData: Partial<Venta>): Observable<Venta>;
  abstract updateVenta(ventaId: number, ventaData: Partial<Venta>): Observable<any>;
  abstract deleteVenta(ventaId: number): Observable<any>;
  abstract getVentaItems(ventaId: number): Observable<VentaItem[]>;
  abstract getVentaItem(ventaItemId: number): Observable<VentaItem>;
  abstract createVentaItem(ventaItemData: Partial<VentaItem>): Observable<VentaItem>;
  abstract updateVentaItem(ventaItemId: number, ventaItemData: Partial<VentaItem>): Observable<any>;
  abstract deleteVentaItem(ventaItemId: number): Observable<boolean>;
  abstract getObservacionesByVentaItem(ventaItemId: number): Observable<any[]>;
  abstract createVentaItemObservacion(data: any): Observable<any>;
  abstract deleteVentaItemObservacion(id: number): Observable<boolean>;
  abstract getVentaItemAdicionales(ventaItemId: number): Observable<any[]>;
  abstract createVentaItemAdicional(data: any): Observable<any>;
  abstract deleteVentaItemAdicional(id: number): Observable<boolean>;
  abstract getVentaItemIngredienteModificaciones(ventaItemId: number): Observable<any[]>;
  abstract createVentaItemIngredienteModificacion(data: any): Observable<any>;
  abstract createVentaItemSabor(data: any): Observable<any>;
  abstract getVentaItemSabores(ventaItemId: number): Observable<any[]>;
  abstract deleteVentaItemSaboresByItem(ventaItemId: number): Observable<any>;
  abstract deleteVentaItemIngredienteModificacion(id: number): Observable<boolean>;
  abstract getComandas(): Observable<any[]>;
  abstract getComandasActivas(): Observable<any[]>;
  abstract getComandasByMesa(mesaId: number): Observable<any[]>;
  abstract getComanda(id: number): Observable<any>;
  abstract createComanda(data: any): Observable<any>;
  abstract updateComanda(id: number, data: any): Observable<any>;
  abstract deleteComanda(id: number): Observable<boolean>;
  abstract getComandasDisponibles(): Observable<any[]>;
  abstract getComandasOcupadas(): Observable<any[]>;
  abstract getComandasBySector(sectorId: number): Observable<any[]>;
  abstract abrirComanda(comandaId: number, data: { mesaId?: number, sectorId?: number, observacion?: string }): Observable<any>;
  abstract cerrarComanda(comandaId: number): Observable<any>;
  abstract createBatchComandas(batchData: any[]): Observable<any[]>;
  abstract getComandaWithVenta(comandaId: number): Observable<any>;
  abstract getPdvGrupoCategorias(): Observable<PdvGrupoCategoria[]>;
  abstract getPdvGrupoCategoria(id: number): Observable<PdvGrupoCategoria>;
  abstract createPdvGrupoCategoria(data: Partial<PdvGrupoCategoria>): Observable<PdvGrupoCategoria>;
  abstract updatePdvGrupoCategoria(id: number, data: Partial<PdvGrupoCategoria>): Observable<PdvGrupoCategoria>;
  abstract deletePdvGrupoCategoria(id: number): Observable<PdvGrupoCategoria>;
  abstract getPdvCategorias(): Observable<PdvCategoria[]>;
  abstract getPdvCategoriasByGrupo(grupoId: number): Observable<PdvCategoria[]>;
  abstract getPdvCategoria(id: number): Observable<PdvCategoria>;
  abstract createPdvCategoria(data: Partial<PdvCategoria>): Observable<PdvCategoria>;
  abstract updatePdvCategoria(id: number, data: Partial<PdvCategoria>): Observable<PdvCategoria>;
  abstract deletePdvCategoria(id: number): Observable<PdvCategoria>;
  abstract getPdvCategoriaItems(): Observable<PdvCategoriaItem[]>;
  abstract getPdvCategoriaItemsByCategoria(categoriaId: number): Observable<PdvCategoriaItem[]>;
  abstract getPdvCategoriaItem(id: number): Observable<PdvCategoriaItem>;
  abstract createPdvCategoriaItem(data: Partial<PdvCategoriaItem>): Observable<PdvCategoriaItem>;
  abstract updatePdvCategoriaItem(id: number, data: Partial<PdvCategoriaItem>): Observable<PdvCategoriaItem>;
  abstract deletePdvCategoriaItem(id: number): Observable<PdvCategoriaItem>;
  abstract getPdvItemProductos(): Observable<PdvItemProducto[]>;
  abstract getPdvItemProductosByItem(itemId: number): Observable<PdvItemProducto[]>;
  abstract getPdvItemProducto(id: number): Observable<PdvItemProducto>;
  abstract createPdvItemProducto(data: Partial<PdvItemProducto>): Observable<PdvItemProducto>;
  abstract updatePdvItemProducto(id: number, data: Partial<PdvItemProducto>): Observable<PdvItemProducto>;
  abstract deletePdvItemProducto(id: number): Observable<PdvItemProducto>;
  abstract getPdvConfig(): Observable<PdvConfig>;
  abstract createPdvConfig(data: Partial<PdvConfig>): Observable<PdvConfig>;
  abstract updatePdvConfig(id: number, data: Partial<PdvConfig>): Observable<PdvConfig>;
  abstract getPdvMesas(): Observable<PdvMesa[]>;
  abstract getPdvMesasActivas(): Observable<PdvMesa[]>;
  abstract getPdvMesasDisponibles(): Observable<PdvMesa[]>;
  abstract getPdvMesasBySector(sectorId: number): Observable<PdvMesa[]>;
  abstract getPdvMesa(id: number): Observable<PdvMesa>;
  abstract createPdvMesa(data: Partial<PdvMesa>): Observable<PdvMesa>;
  abstract createBatchPdvMesas(batchData: Partial<PdvMesa>[]): Observable<PdvMesa[]>;
  abstract updatePdvMesa(id: number, data: Partial<PdvMesa>): Observable<PdvMesa>;
  abstract deletePdvMesa(id: number): Observable<boolean>;
  abstract getSectores(): Observable<Sector[]>;
  abstract getSectoresActivos(): Observable<Sector[]>;
  abstract getSector(id: number): Observable<Sector>;
  abstract createSector(data: Partial<Sector>): Observable<Sector>;
  abstract updateSector(id: number, data: Partial<Sector>): Observable<Sector>;
  abstract deleteSector(id: number): Observable<boolean>;
  abstract getObservaciones(): Observable<Observacion[]>;
  abstract searchObservaciones(search: string): Observable<Observacion[]>;
  abstract getObservacion(id: number): Observable<Observacion>;
  abstract createObservacion(data: Partial<Observacion>): Observable<Observacion>;
  abstract updateObservacion(id: number, data: Partial<Observacion>): Observable<any>;
  abstract deleteObservacion(id: number): Observable<any>;
  abstract getObservacionesByProducto(productoId: number): Observable<ProductoObservacion[]>;
  abstract createProductoObservacion(data: Partial<ProductoObservacion>): Observable<ProductoObservacion>;
  abstract deleteProductoObservacion(id: number): Observable<any>;
  abstract getComboByProducto(productoId: number): Observable<any>;
  abstract createCombo(data: any): Observable<any>;
  abstract updateCombo(id: number, data: any): Observable<any>;
  abstract deleteCombo(id: number): Observable<any>;
  abstract getComboProductos(comboId: number): Observable<any[]>;
  abstract createComboProducto(data: any): Observable<any>;
  abstract updateComboProducto(id: number, data: any): Observable<any>;
  abstract deleteComboProducto(id: number): Observable<any>;
  abstract getAdicionales(): Observable<Adicional[]>;
  abstract getAdicionalesWithFilters(filters: {
    search?: string;
    activo?: boolean | null;
    categoria?: string;
    page?: number;
    pageSize?: number;
  }): Observable<{items: Adicional[], total: number, page: number, pageSize: number}>;
  abstract getAdicional(adicionalId: number): Observable<Adicional>;
  abstract createAdicional(data: Partial<Adicional>): Observable<Adicional>;
  abstract updateAdicional(id: number, data: Partial<Adicional>): Observable<any>;
  abstract deleteAdicional(id: number): Observable<any>;
  abstract getAdicionalWithReceta(adicionalId: number): Observable<Adicional>;
  abstract createRecetaForAdicional(adicionalId: number, recetaData: any): Observable<Receta>;
  abstract updateRecetaForAdicional(adicionalId: number, recetaData: any): Observable<any>;
  abstract deleteRecetaForAdicional(adicionalId: number): Observable<any>;
  abstract getRecetaAdicionalVinculaciones(recetaId: number): Observable<RecetaAdicionalVinculacion[]>;
  abstract getRecetaAdicionalVinculacion(vinculacionId: number): Observable<RecetaAdicionalVinculacion>;
  abstract createRecetaAdicionalVinculacion(data: Partial<RecetaAdicionalVinculacion>): Observable<RecetaAdicionalVinculacion>;
  abstract updateRecetaAdicionalVinculacion(id: number, data: Partial<RecetaAdicionalVinculacion>): Observable<any>;
  abstract deleteRecetaAdicionalVinculacion(id: number): Observable<any>;
  abstract getRecetaIngredientesIntercambiables(recetaIngredienteId: number): Observable<RecetaIngredienteIntercambiable[]>;
  abstract createRecetaIngredienteIntercambiable(data: Partial<RecetaIngredienteIntercambiable>): Observable<RecetaIngredienteIntercambiable>;
  abstract updateRecetaIngredienteIntercambiable(id: number, data: Partial<RecetaIngredienteIntercambiable>): Observable<any>;
  abstract deleteRecetaIngredienteIntercambiable(id: number): Observable<any>;
  abstract getFamilias(): Observable<Familia[]>;
  abstract getFamilia(familiaId: number): Observable<Familia>;
  abstract createFamilia(familiaData: Partial<Familia>): Observable<Familia>;
  abstract updateFamilia(familiaId: number, familiaData: Partial<Familia>): Observable<any>;
  abstract deleteFamilia(familiaId: number): Observable<any>;
  abstract getSubfamilias(): Observable<Subfamilia[]>;
  abstract getSubfamiliasByFamilia(familiaId: number): Observable<Subfamilia[]>;
  abstract getSubfamilia(subfamiliaId: number): Observable<Subfamilia>;
  abstract createSubfamilia(subfamiliaData: Partial<Subfamilia>): Observable<Subfamilia>;
  abstract updateSubfamilia(subfamiliaId: number, subfamiliaData: Partial<Subfamilia>): Observable<any>;
  abstract deleteSubfamilia(subfamiliaId: number): Observable<any>;
  abstract getProductos(): Observable<Producto[]>;
  abstract getProductosWithFilters(filters: {
    search?: string;
    tipo?: string;
    activo?: string;
    esVendible?: string;
    esComprable?: string;
    controlaStock?: string;
    esIngrediente?: string;
    page?: number;
    pageSize?: number;
  }): Observable<{items: Producto[], total: number}>;
  abstract getProducto(productoId: number): Observable<Producto>;
  abstract createProducto(productoData: Partial<Producto>): Observable<Producto>;
  abstract updateProducto(productoId: number, productoData: Partial<Producto>): Observable<any>;
  abstract deleteProducto(productoId: number): Observable<any>;
  abstract getPresentaciones(): Observable<Presentacion[]>;
  abstract getPresentacionesByProducto(productoId: number, page?: number, pageSize?: number, filtroActivo?: string): Observable<any>;
  abstract getPresentacion(presentacionId: number): Observable<any>;
  abstract createPresentacion(presentacionData: Partial<Presentacion>): Observable<Presentacion>;
  abstract updatePresentacion(presentacionId: number, presentacionData: Partial<Presentacion>): Observable<any>;
  abstract deletePresentacion(presentacionId: number): Observable<any>;
  abstract setPresentacionPrincipal(presentacionId: number): Observable<any>;
  abstract togglePresentacionActivo(presentacionId: number): Observable<any>;
  abstract createCodigoBarra(codigoBarraData: Partial<CodigoBarra>): Observable<CodigoBarra>;
  abstract updateCodigoBarra(codigoBarraId: number, codigoBarraData: Partial<CodigoBarra>): Observable<any>;
  abstract deleteCodigoBarra(codigoBarraId: number): Observable<any>;
  abstract getCodigosBarraByPresentacion(presentacionId: number): Observable<CodigoBarra[]>;
  abstract searchProductosByCodigo(codigo: string): Observable<any>;
  abstract getPreciosVenta(): Observable<PrecioVenta[]>;
  abstract getPreciosVentaByPresentacion(presentacionId: number, activo: boolean | null): Observable<PrecioVenta[]>;
  abstract getPreciosVentaByReceta(recetaId: number, activo: boolean | null): Observable<PrecioVenta[]>;
  abstract getPreciosVentaByProducto(productoId: number, activo: boolean | null): Observable<PrecioVenta[]>;
  abstract createPrecioVenta(precioVentaData: Partial<PrecioVenta>): Observable<PrecioVenta>;
  abstract updatePrecioVenta(precioVentaId: number, precioVentaData: Partial<PrecioVenta>): Observable<any>;
  abstract deletePrecioVenta(precioVentaId: number): Observable<any>;
  abstract getPreciosCosto(): Observable<PrecioCosto[]>;
  abstract getPreciosCostoByProducto(productoId: number): Observable<PrecioCosto[]>;
  abstract createPrecioCosto(precioCostoData: Partial<PrecioCosto>): Observable<PrecioCosto>;
  abstract updatePrecioCosto(precioCostoId: number, precioCostoData: Partial<PrecioCosto>): Observable<any>;
  abstract deletePrecioCosto(precioCostoId: number): Observable<any>;
  abstract getRecetas(): Observable<Receta[]>;
  abstract getRecetasWithFilters(filters: {
    search?: string;
    activo?: boolean | null;
    page?: number;
    pageSize?: number;
  }): Observable<{items: Receta[], total: number, page: number, pageSize: number}>;
  abstract getReceta(recetaId: number): Observable<Receta>;
  abstract createReceta(recetaData: Partial<Receta>): Observable<Receta>;
  abstract updateReceta(recetaId: number, recetaData: Partial<Receta>): Observable<any>;
  abstract checkRecetaDependencies(recetaId: number): Observable<{
    receta: { id: number; nombre: string };
    productosVinculados: Array<{ id: number; nombre: string; tipo: string; activo: boolean }>;
  }>;
  abstract deleteReceta(recetaId: number): Observable<any>;
  abstract getRecetasByEstado(activo: boolean | null): Observable<Receta[]>;
  abstract searchRecetasByNombre(nombre: string): Observable<Receta[]>;
  abstract getRecetasWithIngredientes(): Observable<Receta[]>;
  abstract calcularCostoReceta(recetaId: number): Observable<number>;
  abstract actualizarCostoReceta(recetaId: number): Observable<any>;
  abstract getRecetaIngredientes(recetaId: number): Observable<RecetaIngrediente[]>;
  abstract createRecetaIngrediente(recetaIngredienteData: Partial<RecetaIngrediente>): Observable<RecetaIngrediente>;
  abstract updateRecetaIngrediente(recetaIngredienteId: number, recetaIngredienteData: Partial<RecetaIngrediente>): Observable<any>;
  abstract deleteRecetaIngrediente(recetaIngredienteId: number): Observable<any>;
  abstract deleteRecetaIngredienteMultiplesVariaciones(data: {
    recetaIngredienteId: number;
    eliminarDeOtrasVariaciones: boolean;
  }): Observable<any>;
  abstract getRecetaIngredientesActivos(recetaId: number): Observable<RecetaIngrediente[]>;
  abstract calcularCostoIngrediente(recetaIngredienteId: number): Observable<number>;
  abstract validarStockIngrediente(recetaIngredienteId: number): Observable<boolean>;
  abstract getSaboresByProducto(productoId: number): Observable<any[]>;
  abstract createSabor(saborData: {
    nombre: string;
    categoria: string;
    descripcion?: string;
    productoId: number;
    imageUrl?: string | null;
  }): Observable<{ sabor: any; receta: any; mensaje: string }>;
  abstract updateSabor(saborId: number, saborData: Partial<any>): Observable<any>;
  abstract deleteSabor(saborId: number): Observable<{ success: boolean; mensaje: string }>;
  abstract getSaboresEstadisticas(productoId: number): Observable<{
    totalSabores: number;
    saboresActivos: number;
    totalRecetas: number;
    totalVariaciones: number;
  }>;
  abstract getVariacionesByProducto(productoId: number): Observable<any[]>;
  abstract getVariacionesByProductoAndPresentacion(productoId: number, presentacionId: number): Observable<any[]>;
  abstract getVariacionesByReceta(recetaId: number): Observable<any[]>;
  abstract createRecetaPresentacion(variacionData: {
    recetaId: number;
    presentacionId: number;
    saborId: number;
    nombre_generado?: string;
    sku?: string;
    precio_ajuste?: number;
  }): Observable<any>;
  abstract updateRecetaPresentacion(variacionId: number, variacionData: Partial<any>): Observable<any>;
  abstract deleteRecetaPresentacion(variacionId: number): Observable<{ success: boolean; mensaje: string }>;
  abstract bulkUpdateVariaciones(updates: Array<{
    variacionId: number;
    precio_ajuste?: number;
    activo?: boolean;
  }>): Observable<{ success: boolean; actualizadas: number }>;
  abstract recalcularCostoVariacion(variacionId: number): Observable<{
    success: boolean;
    costoAnterior: number;
    costoNuevo: number;
    mensaje: string;
  }>;
  abstract generateVariacionesFaltantes(productoId: number): Observable<{
    success: boolean;
    variacionesGeneradas: number;
    variaciones: any[];
  }>;
  abstract getStockMovimientos(): Observable<StockMovimiento[]>;
  abstract getStockMovimientosByProducto(productoId: number): Observable<StockMovimiento[]>;
  abstract createStockMovimiento(stockMovimientoData: Partial<StockMovimiento>): Observable<StockMovimiento>;
  abstract updateStockMovimiento(stockMovimientoId: number, stockMovimientoData: Partial<StockMovimiento>): Observable<any>;
  abstract deleteStockMovimiento(stockMovimientoId: number): Observable<any>;
  abstract procesarStockVenta(ventaId: number): Observable<any>;
  abstract revertirStockVenta(ventaId: number): Observable<any>;
  abstract searchProductosByNombre(nombre: string, mode?: 'venta' | 'compra'): Observable<Producto[]>;
  abstract getProductosByTipo(tipo: string): Observable<Producto[]>;
  abstract getProductosWithStock(): Observable<Producto[]>;
  abstract getConversionesMoneda(): Observable<ConversionMoneda[]>;
  abstract createConversionMoneda(conversionData: Partial<ConversionMoneda>): Observable<ConversionMoneda>;
  abstract updateConversionMoneda(conversionId: number, conversionData: Partial<ConversionMoneda>): Observable<any>;
  abstract deleteConversionMoneda(conversionId: number): Observable<any>;
  abstract getConfiguracionMonetaria(): Observable<ConfiguracionMonetaria>;
  abstract createConfiguracionMonetaria(configData: Partial<ConfiguracionMonetaria>): Observable<ConfiguracionMonetaria>;
  abstract updateConfiguracionMonetaria(configId: number, configData: Partial<ConfiguracionMonetaria>): Observable<any>;
  abstract getTiposPrecio(): Observable<TipoPrecio[]>;
  abstract getTipoPrecio(tipoPrecioId: number): Observable<TipoPrecio>;
  abstract createTipoPrecio(tipoPrecioData: Partial<TipoPrecio>): Observable<TipoPrecio>;
  abstract updateTipoPrecio(tipoPrecioId: number, tipoPrecioData: Partial<TipoPrecio>): Observable<any>;
  abstract deleteTipoPrecio(tipoPrecioId: number): Observable<any>;
  abstract recalculateAllRecipeCosts(): Observable<any[]>;
  abstract recalculateRecipeCost(recetaId: number): Observable<any>;
  abstract getSabores(): Observable<string[]>;
  abstract createOrUpdateSabor(saborData: any): Observable<{ success: boolean, message: string }>;
  abstract getSaborDetails(categoria: string): Observable<any>;
  abstract getRecetasIdsPorVariacionIds(variacionIds: number[]): Observable<{ [variacionId: number]: number }>;
  abstract getPdvAtajoGrupos(): Observable<any[]>;
  abstract getPdvAtajoGrupo(id: number): Observable<any>;
  abstract createPdvAtajoGrupo(data: any): Observable<any>;
  abstract updatePdvAtajoGrupo(id: number, data: any): Observable<any>;
  abstract deletePdvAtajoGrupo(id: number): Observable<any>;
  abstract reorderPdvAtajoGrupos(orderedIds: number[]): Observable<any>;
  abstract getPdvAtajoItems(): Observable<any[]>;
  abstract getPdvAtajoItem(id: number): Observable<any>;
  abstract getPdvAtajoItemsByGrupo(grupoId: number): Observable<any[]>;
  abstract createPdvAtajoItem(data: any): Observable<any>;
  abstract updatePdvAtajoItem(id: number, data: any): Observable<any>;
  abstract deletePdvAtajoItem(id: number): Observable<any>;
  abstract assignAtajoItemToGrupo(grupoId: number, itemId: number, posicion: number): Observable<any>;
  abstract removeAtajoItemFromGrupo(grupoId: number, itemId: number): Observable<any>;
  abstract reorderAtajoItemsInGrupo(grupoId: number, orderedItemIds: number[]): Observable<any>;
  abstract getPdvAtajoItemProductos(atajoItemId: number): Observable<any[]>;
  abstract assignProductoToAtajoItem(atajoItemId: number, productoId: number, data?: any): Observable<any>;
  abstract removeProductoFromAtajoItem(id: number): Observable<any>;
  abstract reorderProductosInAtajoItem(atajoItemId: number, orderedIds: number[]): Observable<any>;
  abstract getCajasMayor(): Observable<any[]>;
  abstract getCajaMayor(id: number): Observable<any>;
  abstract createCajaMayor(data: any): Observable<any>;
  abstract updateCajaMayor(id: number, data: any): Observable<any>;
  abstract cerrarCajaMayor(id: number): Observable<any>;
  abstract getCajaMayorSaldos(cajaMayorId: number): Observable<any[]>;
  abstract recalcularSaldos(cajaMayorId: number): Observable<any>;
  abstract getCajaMayorMovimientos(cajaMayorId: number, filtros?: any): Observable<any>;
  abstract createCajaMayorMovimiento(data: any): Observable<any>;
  abstract anularCajaMayorMovimiento(id: number, motivo: string): Observable<any>;
  abstract getCajaMayorConfiguracion(cajaMayorId: number): Observable<any>;
  abstract saveCajaMayorConfiguracion(cajaMayorId: number,
    data: {
      formaPagoIds: number[];
      cuentaBancariaIds: number[];
      mostrarCuentasPorPagar?: boolean;
      mostrarCuentasPorCobrar?: boolean;
    }): Observable<any>;
  abstract getCuentaBancariaResumen(cuentaBancariaId: number): Observable<any>;
  abstract getCuentasBancariasResumenes(ids: number[]): Observable<any[]>;
  abstract getCajaMayorCppResumen(): Observable<any[]>;
  abstract getCajaMayorCpcResumen(): Observable<any[]>;
  abstract getGastoCategorias(): Observable<any[]>;
  abstract getGastoCategoria(id: number): Observable<any>;
  abstract createGastoCategoria(data: any): Observable<any>;
  abstract updateGastoCategoria(id: number, data: any): Observable<any>;
  abstract deleteGastoCategoria(id: number): Observable<any>;
  abstract getGastos(filtros?: any): Observable<any[]>;
  abstract getGasto(id: number): Observable<any>;
  abstract createGasto(data: any): Observable<any>;
  abstract anularGasto(id: number, motivo: string): Observable<any>;
  abstract editGasto(gastoId: number, data: any): Observable<any>;
  abstract editCajaMayorMovimiento(movId: number, data: any): Observable<any>;
  abstract getGastosProgramados(): Observable<any[]>;
  abstract getRetirosCaja(filtros?: any): Observable<any[]>;
  abstract getRetiroCaja(id: number): Observable<any>;
  abstract createRetiroCaja(data: any): Observable<any>;
  abstract ingresarRetiroCaja(retiroId: number, cajaMayorId: number): Observable<any>;
  abstract getCuentasBancarias(): Observable<any[]>;
  abstract getCuentaBancaria(id: number): Observable<any>;
  abstract createCuentaBancaria(data: any): Observable<any>;
  abstract updateCuentaBancaria(id: number, data: any): Observable<any>;
  abstract deleteCuentaBancaria(id: number): Observable<any>;
  abstract getMaquinasPos(): Observable<any[]>;
  abstract getMaquinaPos(id: number): Observable<any>;
  abstract createMaquinaPos(data: any): Observable<any>;
  abstract updateMaquinaPos(id: number, data: any): Observable<any>;
  abstract deleteMaquinaPos(id: number): Observable<any>;
  abstract getAcreditacionesPos(filtros?: any): Observable<any>;
  abstract getAcreditacionPos(id: number): Observable<any>;
  abstract createAcreditacionPos(data: any): Observable<any>;
  abstract procesarAcreditacionesAuto(): Observable<any>;
  abstract verificarAcreditacionPos(id: number, montoAcreditado: number): Observable<any>;
  abstract getAcreditacionesPendientes(): Observable<any[]>;
  abstract acreditarTransferenciaBancaria(payload: any): Observable<any>;
  abstract getCompraCategorias(): Observable<any[]>;
  abstract createCompraCategoria(data: any): Observable<any>;
  abstract updateCompraCategoria(id: number, data: any): Observable<any>;
  abstract deleteCompraCategoria(id: number): Observable<any>;
  abstract getCompraCuotas(compraId: number): Observable<any[]>;
  abstract setCompraCuotas(compraId: number, cuotas: any[]): Observable<any[]>;
  abstract pagarCompraCuota(payload: any): Observable<any>;
  abstract getCuentasPorPagar(filtros?: any): Observable<any>;
  abstract getCuentaPorPagar(id: number): Observable<any>;
  abstract createCuentaPorPagar(data: any): Observable<any>;
  abstract updateCuentaPorPagar(id: number, data: any): Observable<any>;
  abstract cancelarCuentaPorPagar(id: number): Observable<any>;
  abstract getCuentaPorPagarCuotas(cppId: number): Observable<any[]>;
  abstract pagarCppCuota(payload: any): Observable<any>;
  abstract pagarCuotasComprasLote(payload: any): Observable<any>;
  abstract getCuotasPendientesCompras(filtros?: any): Observable<any[]>;
  abstract cancelarCppCuota(payload: any): Observable<any>;
  abstract getDashboardShortcuts(dashboardKey?: string): Observable<any[]>;
  abstract createDashboardShortcut(data: any): Observable<any>;
  abstract updateDashboardShortcut(id: number, data: any): Observable<any>;
  abstract deleteDashboardShortcut(id: number): Observable<any>;
  abstract getEntradaVariaCategorias(): Observable<any[]>;
  abstract getEntradaVariaCategoria(id: number): Observable<any>;
  abstract createEntradaVariaCategoria(data: any): Observable<any>;
  abstract updateEntradaVariaCategoria(id: number, data: any): Observable<any>;
  abstract deleteEntradaVariaCategoria(id: number): Observable<any>;
  abstract getEntradasVarias(filtros?: any): Observable<any>;
  abstract getEntradaVaria(id: number): Observable<any>;
  abstract createEntradaVaria(data: any): Observable<any>;
  abstract anularEntradaVaria(id: number, motivo: string): Observable<any>;
  abstract getOperacionFinancieraCategorias(): Observable<any[]>;
  abstract getOperacionFinancieraCategoria(id: number): Observable<any>;
  abstract createOperacionFinancieraCategoria(data: any): Observable<any>;
  abstract updateOperacionFinancieraCategoria(id: number, data: any): Observable<any>;
  abstract deleteOperacionFinancieraCategoria(id: number): Observable<any>;
  abstract getOperacionesFinancieras(filtros?: any): Observable<any>;
  abstract getOperacionFinanciera(id: number): Observable<any>;
  abstract createOperacionFinanciera(data: any): Observable<any>;
  abstract anularOperacionFinanciera(id: number, motivo: string): Observable<any>;
  abstract getMovimientosCuentaBancaria(cuentaBancariaId: number, filtros?: any): Observable<any>;
  abstract createMovimientoBancario(data: any): Observable<any>;
  abstract getChequeras(): Observable<any[]>;
  abstract getChequera(id: number): Observable<any>;
  abstract createChequera(data: any): Observable<any>;
  abstract updateChequera(id: number, data: any): Observable<any>;
  abstract deleteChequera(id: number): Observable<any>;
  abstract getCheques(filtros?: any): Observable<any>;
  abstract getCheque(id: number): Observable<any>;
  abstract emitirCheque(data: any): Observable<any>;
  abstract cobrarCheque(id: number, data?: any): Observable<any>;
  abstract anularCheque(id: number, motivo: string): Observable<any>;
  abstract getPermissions(modulo?: string): Observable<any[]>;
  abstract getAllPermissions(): Observable<any[]>;
  abstract createPermission(data: any): Observable<any>;
  abstract updatePermission(id: number, data: any): Observable<any>;
  abstract deletePermission(id: number): Observable<any>;
  abstract getRolePermissions(roleId: number): Observable<any[]>;
  abstract setRolePermissions(roleId: number, permissionIds: number[]): Observable<any>;
  abstract getPermissionsByUser(userId: number): Observable<any[]>;
  abstract seedPermissions(): Observable<any>;
  abstract getConfiguracionesRrhh(): Observable<any[]>;
  abstract getConfiguracionRrhh(clave: string): Observable<any>;
  abstract createConfiguracionRrhh(data: any): Observable<any>;
  abstract updateConfiguracionRrhh(id: number, data: any): Observable<any>;
  abstract deleteConfiguracionRrhh(id: number): Observable<any>;
  abstract seedConfiguracionRrhh(): Observable<any>;
  abstract getCargos(): Observable<any[]>;
  abstract getCargo(id: number): Observable<any>;
  abstract createCargo(data: any): Observable<any>;
  abstract updateCargo(id: number, data: any): Observable<any>;
  abstract deleteCargo(id: number): Observable<any>;
  abstract getFuncionarios(filtros?: any): Observable<any[]>;
  abstract getFuncionario(id: number): Observable<any>;
  abstract createFuncionario(data: any): Observable<any>;
  abstract updateFuncionario(id: number, data: any): Observable<any>;
  abstract cambiarCargoFuncionario(id: number, data: any): Observable<any>;
  abstract cambiarSalarioFuncionario(id: number, data: any): Observable<any>;
  abstract egresarFuncionario(id: number, data: any): Observable<any>;
  abstract getHistoricoCargos(funcionarioId: number): Observable<any[]>;
  abstract getHistoricoSalarios(funcionarioId: number): Observable<any[]>;
  abstract getFuncionarioDocumentos(funcionarioId: number): Observable<any[]>;
  abstract uploadFuncionarioDocumento(payload: any): Observable<any>;
  abstract deleteFuncionarioDocumento(id: number): Observable<any>;
  abstract getFuncionarioDocumentoBase64(id: number): Observable<any>;
  abstract updateFuncionarioDocumento(id: number, data: any): Observable<any>;
  abstract getTurnos(): Observable<any[]>;
  abstract getTurno(id: number): Observable<any>;
  abstract createTurno(data: any): Observable<any>;
  abstract updateTurno(id: number, data: any): Observable<any>;
  abstract deleteTurno(id: number): Observable<any>;
  abstract asignarTurnoFuncionario(data: any): Observable<any>;
  abstract cerrarFuncionarioTurno(id: number, fechaHasta?: Date): Observable<any>;
  abstract updateFuncionarioTurno(id: number, data: any): Observable<any>;
  abstract getFuncionarioTurnos(funcionarioId: number): Observable<any[]>;
  abstract getAsistencias(filtros?: any): Observable<any[]>;
  abstract getAsistencia(id: number): Observable<any>;
  abstract createAsistencia(data: any): Observable<any>;
  abstract updateAsistencia(id: number, data: any): Observable<any>;
  abstract justificarAsistencia(id: number, data: any): Observable<any>;
  abstract marcarAsistenciaMasiva(payload: any): Observable<any>;
  abstract getPenalizaciones(filtros?: any): Observable<any[]>;
  abstract createPenalizacion(data: any): Observable<any>;
  abstract updatePenalizacion(data: any): Observable<any>;
  abstract anularPenalizacion(id: number): Observable<any>;
  abstract getFeriados(anio?: number): Observable<any[]>;
  abstract createFeriado(data: any): Observable<any>;
  abstract updateFeriado(id: number, data: any): Observable<any>;
  abstract deleteFeriado(id: number): Observable<any>;
  abstract getHorasExtra(filtros?: any): Observable<any[]>;
  abstract createHoraExtra(data: any): Observable<any>;
  abstract anularHoraExtra(id: number): Observable<any>;
  abstract getMotivosVale(): Observable<any[]>;
  abstract createMotivoVale(data: any): Observable<any>;
  abstract updateMotivoVale(id: number, data: any): Observable<any>;
  abstract deleteMotivoVale(id: number): Observable<any>;
  abstract getVales(filtros?: any): Observable<any[]>;
  abstract getValesPendientesDescuento(funcionarioId: number): Observable<any[]>;
  abstract createVale(data: any): Observable<any>;
  abstract confirmarVale(id: number, payload: any): Observable<any>;
  abstract anularVale(id: number, motivo: string): Observable<any>;
  abstract marcarValeDescontado(id: number, liquidacionId: number): Observable<any>;
  abstract getLiquidacionConceptos(): Observable<any[]>;
  abstract seedLiquidacionConceptos(): Observable<any>;
  abstract updateLiquidacionConcepto(id: number, data: any): Observable<any>;
  abstract getLiquidacionesSueldo(filtros?: any): Observable<any[]>;
  abstract getLiquidacionSueldo(id: number): Observable<any>;
  abstract generarLiquidacionBorrador(payload: any): Observable<any>;
  abstract agregarItemLiquidacion(liquidacionId: number, data: any): Observable<any>;
  abstract eliminarItemLiquidacion(itemId: number): Observable<any>;
  abstract aprobarLiquidacionSueldo(id: number): Observable<any>;
  abstract volverBorradorLiquidacionSueldo(id: number): Observable<any>;
  abstract pagarLiquidacionSueldo(id: number, payload: any): Observable<any>;
  abstract anularLiquidacionSueldo(id: number, motivo: string): Observable<any>;
  abstract getBonos(filtros?: any): Observable<any[]>;
  abstract createBono(data: any): Observable<any>;
  abstract anularBono(id: number): Observable<any>;
  abstract getAguinaldos(filtros?: any): Observable<any[]>;
  abstract calcularAguinaldosAnio(anio: number): Observable<any>;
  abstract getVacaciones(filtros?: any): Observable<any[]>;
  abstract getVacacion(id: number): Observable<any>;
  abstract generarVacacionesFuncionario(funcionarioId: number): Observable<any>;
  abstract programarVacacionPeriodo(payload: any): Observable<any>;
  abstract marcarPeriodoGozado(periodoId: number): Observable<any>;
  abstract cancelarVacacionPeriodo(periodoId: number): Observable<any>;
  abstract getLiquidacionesFinal(filtros?: any): Observable<any[]>;
  abstract getLiquidacionFinal(id: number): Observable<any>;
  abstract generarLiquidacionFinal(payload: any): Observable<any>;
  abstract aprobarLiquidacionFinal(id: number): Observable<any>;
  abstract pagarLiquidacionFinal(id: number, payload: any): Observable<any>;
  abstract getReglasComision(filtros?: any): Observable<any[]>;
  abstract getReglaComision(id: number): Observable<any>;
  abstract createReglaComision(data: any): Observable<any>;
  abstract updateReglaComision(id: number, data: any): Observable<any>;
  abstract deleteReglaComision(id: number): Observable<any>;
  abstract getFuncionariosRegla(reglaId: number): Observable<any[]>;
  abstract asignarFuncionarioRegla(data: any): Observable<any>;
  abstract desasignarFuncionarioRegla(asignacionId: number): Observable<any>;
  abstract getLiquidacionesComision(filtros?: any): Observable<any[]>;
  abstract getLiquidacionComision(id: number): Observable<any>;
  abstract generarLiquidacionComision(payload: any): Observable<any>;
  abstract generarLiquidacionesComisionMes(periodo: string): Observable<any>;
  abstract aprobarLiquidacionComision(id: number): Observable<any>;
  abstract agregarItemManualLiquidacionComision(payload: any): Observable<any>;
  abstract eliminarItemLiquidacionComision(itemId: number): Observable<any>;
  abstract anularLiquidacionComision(id: number): Observable<any>;
  abstract getEquiposComision(filtros?: any): Observable<any[]>;
  abstract getEquipoComision(id: number): Observable<any>;
  abstract createEquipoComision(data: any): Observable<any>;
  abstract updateEquipoComision(id: number, data: any): Observable<any>;
  abstract deleteEquipoComision(id: number): Observable<any>;
  abstract agregarMiembroEquipo(payload: any): Observable<any>;
  abstract eliminarMiembroEquipo(miembroId: number): Observable<any>;
  abstract actualizarPorcentajeMiembro(payload: any): Observable<any>;
  abstract asignarReglaEquipo(payload: any): Observable<any>;
  abstract desasignarReglaEquipo(asignacionId: number): Observable<any>;
  abstract evaluarEquipoPeriodo(payload: any): Observable<any>;
  abstract getCuentasPorCobrar(filtros?: any): Observable<any>;
  abstract getCuentaPorCobrar(id: number): Observable<any>;
  abstract createCuentaPorCobrar(data: any): Observable<any>;
  abstract updateCuentaPorCobrar(id: number, data: any): Observable<any>;
  abstract cancelarCuentaPorCobrar(payload: any): Observable<any>;
  abstract getCuentaPorCobrarCuotas(cpcId: number): Observable<any[]>;
  abstract cobrarCpcCuota(payload: any): Observable<any>;
  abstract anularCobroCpcCuota(payload: any): Observable<any>;
  abstract recalcularSaldoCliente(clienteId: number): Observable<any>;
  abstract getMovimientosCliente(clienteId: number, filtros?: any): Observable<any>;
  abstract getSaldoCliente(clienteId: number): Observable<any>;
  abstract getNotificacionesRrhh(filtros?: any): Observable<any[]>;
  abstract marcarNotificacionLeida(id: number): Observable<any>;
  abstract marcarTodasNotificacionesLeidas(usuarioId?: number): Observable<any>;
  abstract generarNotificacionesRrhh(): Observable<any>;
  abstract countNotificacionesNoLeidas(usuarioId?: number): Observable<any>;
  abstract getDashboardRrhhKpis(periodo: string): Observable<any>;
  abstract getDashboardVentasKpis(rango?: string): Observable<any>;
  abstract getDashboardComprasKpis(): Observable<any>;
  abstract getDashboardProductosKpis(): Observable<any>;
  abstract getDashboardFinancieroKpis(): Observable<any>;
  abstract getDashboardCajaMayorKpis(): Observable<any>;
  abstract getReporteLiquidacionesMesData(periodo: string): Observable<any>;
  abstract exportReporteLiquidacionesMesExcel(periodo: string): Observable<any>;
  abstract exportReporteLiquidacionesMesPdf(periodo: string): Observable<any>;
  abstract getReporteAsistenciaMesData(periodo: string, funcionarioId?: number): Observable<any>;
  abstract exportReporteAsistenciaMesExcel(periodo: string, funcionarioId?: number): Observable<any>;
  abstract getReporteValesMesData(periodo: string): Observable<any>;
  abstract exportReporteValesMesExcel(periodo: string): Observable<any>;
  abstract getReportePrestamosActivosData(): Observable<any>;
  abstract exportReportePrestamosActivosExcel(): Observable<any>;
  abstract getReporteComisionesMesData(periodo: string): Observable<any>;
  abstract exportReporteComisionesMesExcel(periodo: string): Observable<any>;
  abstract exportReciboLiquidacionPdf(liquidacionId: number): Observable<any>;
  abstract getReporteAguinaldoAnualData(anio: number): Observable<any>;
  abstract exportReporteAguinaldoAnualExcel(anio: number): Observable<any>;
  abstract exportReporteAguinaldoAnualPdf(anio: number): Observable<any>;
  abstract getReporteResumenIpsData(periodo: string): Observable<any>;
  abstract exportReporteResumenIpsExcel(periodo: string): Observable<any>;
}
